#!/usr/bin/env python3
"""
Golden model for the two-design spike detector.

Function (both designs):  spike = (A*B + C*D) > Vth
  A,B,C,D : WIDTH-bit unsigned   (WIDTH=5 -> 0..31)
  Vth     : VW-bit unsigned      (VW=11    -> 0..2047, covers max S = 31*31*2 = 1922)

Design 1 (baseline) computes the exact integer math -> spike_exact.
Design 2 (log / LNS, K=1) computes an approximate result in the log2 domain with
one fraction bit (Mitchell-style leading-one detector + 1 mantissa bit) -> spike_k1.

EVERYTHING here is integer arithmetic in "half-log2 units" (units of 0.5), so the
Verilog RTL can be made bit-exact to spike_k1.  The F(d) add-correction ROM is
generated here and emitted as rtl/lns_ftable.v -> single source of truth, model and
hardware cannot drift.
"""
import math, os, csv, argparse
import numpy as np

WIDTH = 5            # input bit width
K     = 1            # fraction bits kept in the log converter
VW    = 11           # Vth bit width
IN_MAX  = (1 << WIDTH) - 1          # 31
VTH_MAX = (1 << VW) - 1             # 2047
S_MAX   = IN_MAX*IN_MAX*2           # 1922

HERE   = os.path.dirname(os.path.abspath(__file__))
ROOT   = os.path.dirname(HERE)
RTL    = os.path.join(ROOT, "rtl")
VERIF  = os.path.join(ROOT, "verif")
REPORT = os.path.join(ROOT, "report")

# ---------------------------------------------------------------------------
# K=1 log converter (scalar reference).  Returns (is_zero, L) with
#   L = 2*floor(log2 v) + fracbit          (integer, half-log2 units)
# fracbit is the single mantissa bit just below the leading one (K=1).
# ---------------------------------------------------------------------------
def log_k1(v):
    if v == 0:
        return (1, 0)
    e = v.bit_length() - 1                 # floor(log2 v)
    frac = 0 if e == 0 else ((v >> (e - 1)) & 1)
    return (0, 2 * e + frac)

# ---------------------------------------------------------------------------
# F(d) = log2(1 + 2^-d) add-correction, in half-log2 units, rounded to int.
# d is itself a half-log2 quantity (|x-y| in half units), so real d = d/2.
# dmax = max |X-Y| = max(L(A)+L(B)) = 2*(L for v in 1..31)max = 2*9 = 18.
# ---------------------------------------------------------------------------
def build_ftab(dmax):
    tab = []
    for d in range(dmax + 1):
        val = 2.0 * math.log2(1.0 + 2.0 ** (-(d / 2.0)))
        tab.append(int(round(val)))
    return tab

DMAX = 2 * (2 * (WIDTH - 1) + 1)           # = 18 for WIDTH=5
FTAB = build_ftab(DMAX)

# ---------------------------------------------------------------------------
# Scalar spike models (the authoritative specs).
# ---------------------------------------------------------------------------
def spike_exact(A, B, C, D, Vth):
    return 1 if (A * B + C * D) > Vth else 0

def spike_k1(A, B, C, D, Vth):
    zA, la = log_k1(A); zB, lb = log_k1(B)
    zC, lc = log_k1(C); zD, ld = log_k1(D)
    zx = zA or zB                          # term A*B is zero
    zy = zC or zD                          # term C*D is zero
    X = la + lb                            # log2(A)+log2(B) in half-units
    Y = lc + ld
    if zx and zy:
        s_zero, s = 1, 0
    elif zx:
        s_zero, s = 0, Y
    elif zy:
        s_zero, s = 0, X
    else:
        s_zero = 0
        d = abs(X - Y)
        s = max(X, Y) + FTAB[d]            # LNS add: max + F(|x-y|)
    zv, lv = log_k1(Vth)
    if zv:                                 # Vth == 0  -> spike = (S > 0)
        return 0 if s_zero else 1
    if s_zero:                             # S == 0, Vth > 0
        return 0
    return 1 if s > lv else 0              # compare in log domain

# ---------------------------------------------------------------------------
# Emit rtl/lns_ftable.v from FTAB (single source of truth).
# ---------------------------------------------------------------------------
def emit_ftable_v():
    os.makedirs(RTL, exist_ok=True)
    idx_bits = max(1, (DMAX).bit_length())         # index width for d (0..18 -> 5)
    fbits    = max(1, (max(FTAB)).bit_length())    # value width      (0..2  -> 2)
    path = os.path.join(RTL, "lns_ftable.v")
    with open(path, "w") as f:
        f.write("// AUTO-GENERATED by model/model.py -- DO NOT EDIT.\n")
        f.write("// F(d) = round( 2*log2(1 + 2^-(d/2)) ), half-log2 units.  K=%d.\n" % K)
        f.write("module lns_ftable(input [%d:0] d, output reg [%d:0] f);\n"
                % (idx_bits - 1, fbits - 1))
        f.write("  always @* begin\n    case (d)\n")
        for d, val in enumerate(FTAB):
            f.write("      %d'd%d: f = %d'd%d;\n" % (idx_bits, d, fbits, val))
        f.write("      default: f = %d'd0;\n" % fbits)
        f.write("    endcase\n  end\nendmodule\n")
    return path, idx_bits, fbits

# ---------------------------------------------------------------------------
# Vectorised full-space disagreement + vector-file generation.
# ---------------------------------------------------------------------------
VTHS = [0, 1, 31, 100, 256, 500, 900, 961, 1000, 1500, 1922, 2000]

def vec_log_tables(nmax):
    """Lookup arrays z[v], L[v] for v in 0..nmax."""
    z = np.zeros(nmax + 1, dtype=np.int64)
    L = np.zeros(nmax + 1, dtype=np.int64)
    for v in range(nmax + 1):
        zz, ll = log_k1(v)
        z[v] = zz; L[v] = ll
    return z, L

def compute_full():
    """Return flattened A,B,C,D and per-input k1 intermediates over full space."""
    vals = np.arange(IN_MAX + 1, dtype=np.int64)
    A, B, C, D = np.meshgrid(vals, vals, vals, vals, indexing="ij")
    A = A.ravel(); B = B.ravel(); C = C.ravel(); D = D.ravel()
    zin, Lin = vec_log_tables(IN_MAX)
    X = Lin[A] + Lin[B]
    Y = Lin[C] + Lin[D]
    zx = (zin[A] | zin[B]).astype(bool)
    zy = (zin[C] | zin[D]).astype(bool)
    ftab = np.array(FTAB, dtype=np.int64)
    d = np.abs(X - Y)
    s_both = np.maximum(X, Y) + ftab[d]
    s_zero = zx & zy
    s = np.where(zx & zy, 0, np.where(zx, Y, np.where(zy, X, s_both)))
    Sexact = A * B + C * D
    return A, B, C, D, Sexact, s, s_zero

def k1_spike_vec(s, s_zero, Vth):
    zv, lv = log_k1(int(Vth))
    if zv:                                   # Vth == 0
        return (~s_zero).astype(np.int8)
    out = np.where(s_zero, 0, (s > lv).astype(np.int8)).astype(np.int8)
    return out

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sample-per-vth", type=int, default=4000)
    ap.add_argument("--seed", type=int, default=1234)
    args = ap.parse_args()

    os.makedirs(VERIF, exist_ok=True); os.makedirs(REPORT, exist_ok=True)

    fpath, idx_bits, fbits = emit_ftable_v()
    print("FTAB (d=0..%d):" % DMAX, FTAB)
    print("emitted", fpath, "(index %d bits, value %d bits)" % (idx_bits, fbits))

    A, B, C, D, Sexact, s, s_zero = compute_full()
    ncombo = A.size
    print("full input space: %d combos (%d^4)" % (ncombo, IN_MAX + 1))

    rng = np.random.default_rng(args.seed)

    total_pairs = 0
    total_disagree = 0
    per_vth = []
    # rows collected for vectors.csv
    rows = []   # each: (A,B,C,D,Vth,exp_exact,exp_k1)

    for Vth in VTHS:
        exact = (Sexact > Vth).astype(np.int8)
        k1    = k1_spike_vec(s, s_zero, Vth)
        dis   = int(np.count_nonzero(exact != k1))
        per_vth.append((Vth, dis, ncombo, 100.0 * dis / ncombo))
        total_pairs += ncombo
        total_disagree += dis

        # ---- pick vectors for this Vth: random sample + boundary + disagreement ----
        picks = set()
        # random sample
        idx = rng.choice(ncombo, size=min(args.sample_per_vth, ncombo), replace=False)
        picks.update(idx.tolist())
        # boundary: exact S within +/-4 of Vth (stress the comparator)
        near = np.nonzero(np.abs(Sexact - Vth) <= 4)[0]
        if near.size > 800:
            near = rng.choice(near, size=800, replace=False)
        picks.update(near.tolist())
        # disagreement cases (stress RTL against k1 exactly where it matters)
        dif = np.nonzero(exact != k1)[0]
        if dif.size > 800:
            dif = rng.choice(dif, size=800, replace=False)
        picks.update(dif.tolist())

        for i in picks:
            rows.append((int(A[i]), int(B[i]), int(C[i]), int(D[i]), int(Vth),
                         int(exact[i]), int(k1[i])))

    disagree_rate = 100.0 * total_disagree / total_pairs

    # write vectors.csv
    vpath = os.path.join(VERIF, "vectors.csv")
    with open(vpath, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["A", "B", "C", "D", "Vth", "exp_exact", "exp_k1"])
        w.writerows(rows)
    print("wrote %s : %d vectors" % (vpath, len(rows)))

    # report
    lines = []
    lines.append("Design-2 (K=1 log/LNS) accuracy vs Design-1 (exact multiplier)")
    lines.append("=" * 62)
    lines.append("WIDTH=%d  K=%d  VW=%d   full space=%d combos x %d Vth values"
                 % (WIDTH, K, VW, ncombo, len(VTHS)))
    lines.append("F(d) ROM (half-log2 units): %s" % FTAB)
    lines.append("")
    lines.append("Per-Vth disagreement (spike_k1 != spike_exact):")
    lines.append("  %-8s %-12s %-12s %s" % ("Vth", "disagree", "total", "rate%"))
    for Vth, dis, tot, rate in per_vth:
        lines.append("  %-8d %-12d %-12d %.4f" % (Vth, dis, tot, rate))
    lines.append("")
    lines.append("OVERALL disagreement rate = %d / %d = %.4f %%"
                 % (total_disagree, total_pairs, disagree_rate))
    lines.append("(This is the accuracy cost of dropping the multiplier. A disagreement")
    lines.append(" is only an RTL bug if the RTL output != spike_k1 -- checked in Phase 4.)")
    txt = "\n".join(lines) + "\n"
    apath = os.path.join(REPORT, "model_accuracy.txt")
    with open(apath, "w") as f:
        f.write(txt)
    print(txt)
    print("wrote", apath)

if __name__ == "__main__":
    main()
