// AUTO-GENERATED by model/model.py -- DO NOT EDIT.
// F(d) = round( 2*log2(1 + 2^-(d/2)) ), half-log2 units.  K=1.
module lns_ftable(input [4:0] d, output reg [1:0] f);
  always @* begin
    case (d)
      5'd0: f = 2'd2;
      5'd1: f = 2'd2;
      5'd2: f = 2'd1;
      5'd3: f = 2'd1;
      5'd4: f = 2'd1;
      5'd5: f = 2'd0;
      5'd6: f = 2'd0;
      5'd7: f = 2'd0;
      5'd8: f = 2'd0;
      5'd9: f = 2'd0;
      5'd10: f = 2'd0;
      5'd11: f = 2'd0;
      5'd12: f = 2'd0;
      5'd13: f = 2'd0;
      5'd14: f = 2'd0;
      5'd15: f = 2'd0;
      5'd16: f = 2'd0;
      5'd17: f = 2'd0;
      5'd18: f = 2'd0;
      default: f = 2'd0;
    endcase
  end
endmodule
