// AUTO-GENERATED by model/model.py -- DO NOT EDIT.
// F(d) = round( 2*log2(1 + 2^-(d/2)) ), half-log2 units.  K=1.
module lns_ftable(input [7:0] d, output reg [1:0] f);
  always @* begin
    case (d)
      8'd0: f = 2'd2;
      8'd1: f = 2'd2;
      8'd2: f = 2'd1;
      8'd3: f = 2'd1;
      8'd4: f = 2'd1;
      8'd5: f = 2'd0;
      8'd6: f = 2'd0;
      8'd7: f = 2'd0;
      8'd8: f = 2'd0;
      8'd9: f = 2'd0;
      8'd10: f = 2'd0;
      8'd11: f = 2'd0;
      8'd12: f = 2'd0;
      8'd13: f = 2'd0;
      8'd14: f = 2'd0;
      8'd15: f = 2'd0;
      8'd16: f = 2'd0;
      8'd17: f = 2'd0;
      8'd18: f = 2'd0;
      8'd19: f = 2'd0;
      8'd20: f = 2'd0;
      8'd21: f = 2'd0;
      8'd22: f = 2'd0;
      8'd23: f = 2'd0;
      8'd24: f = 2'd0;
      8'd25: f = 2'd0;
      8'd26: f = 2'd0;
      8'd27: f = 2'd0;
      8'd28: f = 2'd0;
      8'd29: f = 2'd0;
      8'd30: f = 2'd0;
      8'd31: f = 2'd0;
      8'd32: f = 2'd0;
      8'd33: f = 2'd0;
      8'd34: f = 2'd0;
      8'd35: f = 2'd0;
      8'd36: f = 2'd0;
      8'd37: f = 2'd0;
      8'd38: f = 2'd0;
      8'd39: f = 2'd0;
      8'd40: f = 2'd0;
      8'd41: f = 2'd0;
      8'd42: f = 2'd0;
      8'd43: f = 2'd0;
      8'd44: f = 2'd0;
      8'd45: f = 2'd0;
      8'd46: f = 2'd0;
      default: f = 2'd0;
    endcase
  end
endmodule
