/* Generated by Yosys 0.55 (git sha1 60f126cd0, ccache clang 18.1.3 -O3 -flto -flto) */

module log_detector(clk, A, B, C, D, Vth, spike);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  input [4:0] A;
  wire [4:0] A;
  wire [5:0] \ADD.X ;
  wire [5:0] \ADD.Y ;
  wire [5:0] \ADD.d ;
  wire [5:0] \ADD.mx ;
  wire [6:0] \ADD.s ;
  wire [4:0] Ar;
  input [4:0] B;
  wire [4:0] B;
  wire [4:0] Br;
  input [4:0] C;
  wire [4:0] C;
  wire [4:0] Cr;
  input [4:0] D;
  wire [4:0] D;
  wire [4:0] Dr;
  wire [31:0] \LA.i ;
  wire [4:0] \LA.v ;
  wire [31:0] \LB.i ;
  wire [4:0] \LB.v ;
  wire [31:0] \LC.i ;
  wire [4:0] \LC.v ;
  wire [31:0] \LD.i ;
  wire [4:0] \LD.v ;
  wire [31:0] \LV.i ;
  wire [10:0] \LV.v ;
  wire [10:0] Vr;
  input [10:0] Vth;
  wire [10:0] Vth;
  wire [4:0] X;
  wire [4:0] Y;
  input clk;
  wire clk;
  wire [6:0] s;
  output spike;
  wire spike;
  wire spike_c;
  sky130_fd_sc_hd__clkinv_1 _178_ (
    .A(Cr[4]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__clkinv_1 _179_ (
    .A(Ar[0]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__clkinv_1 _180_ (
    .A(Br[0]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__clkinv_1 _181_ (
    .A(Vr[6]),
    .Y(_114_)
  );
  sky130_fd_sc_hd__clkinv_1 _182_ (
    .A(Vr[5]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nor2_1 _183_ (
    .A(Br[3]),
    .B(Br[2]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nor3_1 _184_ (
    .A(Br[0]),
    .B(Br[4]),
    .C(Br[1]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__or4_1 _185_ (
    .A(Ar[0]),
    .B(Ar[3]),
    .C(Ar[4]),
    .D(Ar[2]),
    .X(_118_)
  );
  sky130_fd_sc_hd__nor2_1 _186_ (
    .A(Ar[1]),
    .B(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a21oi_1 _187_ (
    .A1(_116_),
    .A2(_117_),
    .B1(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nor2_1 _188_ (
    .A(Cr[3]),
    .B(Cr[2]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__or4_1 _189_ (
    .A(Cr[3]),
    .B(Cr[4]),
    .C(Cr[2]),
    .D(Cr[0]),
    .X(_122_)
  );
  sky130_fd_sc_hd__nor2_1 _190_ (
    .A(Dr[3]),
    .B(Dr[2]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nor2_1 _191_ (
    .A(Dr[0]),
    .B(Dr[4]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nand2_1 _192_ (
    .A(_123_),
    .B(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__o22a_1 _193_ (
    .A1(Cr[1]),
    .A2(_122_),
    .B1(_125_),
    .B2(Dr[1]),
    .X(_126_)
  );
  sky130_fd_sc_hd__o22ai_1 _194_ (
    .A1(Cr[1]),
    .A2(_122_),
    .B1(_125_),
    .B2(Dr[1]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _195_ (
    .A(_120_),
    .SLEEP(_126_),
    .X(_128_)
  );
  sky130_fd_sc_hd__or3_1 _196_ (
    .A(Vr[9]),
    .B(Vr[10]),
    .C(Vr[8]),
    .X(_129_)
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(Vr[7]),
    .B(Vr[6]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nor4_1 _198_ (
    .A(Vr[7]),
    .B(Vr[6]),
    .C(Vr[5]),
    .D(Vr[4]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand2b_1 _199_ (
    .A_N(_129_),
    .B(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor2_1 _200_ (
    .A(Vr[3]),
    .B(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nor4b_1 _201_ (
    .A(Vr[2]),
    .B(Vr[1]),
    .C(Vr[0]),
    .D_N(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand2_1 _202_ (
    .A(_128_),
    .B(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__or4_1 _203_ (
    .A(Cr[4]),
    .B(Dr[4]),
    .C(_121_),
    .D(_123_),
    .X(_136_)
  );
  sky130_fd_sc_hd__o22ai_1 _204_ (
    .A1(Cr[4]),
    .A2(_121_),
    .B1(_123_),
    .B2(Dr[4]),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nand2_1 _205_ (
    .A(_136_),
    .B(_137_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand2b_1 _206_ (
    .A_N(Dr[4]),
    .B(Dr[3]),
    .Y(_139_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _207_ (
    .A(Dr[1]),
    .SLEEP(Dr[4]),
    .X(_140_)
  );
  sky130_fd_sc_hd__or4b_1 _208_ (
    .A(Dr[3]),
    .B(Dr[4]),
    .C(Dr[2]),
    .D_N(Dr[1]),
    .X(_141_)
  );
  sky130_fd_sc_hd__nand2_1 _209_ (
    .A(_139_),
    .B(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _210_ (
    .A1(_111_),
    .A2(Cr[1]),
    .B1(Cr[3]),
    .Y(_143_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _211_ (
    .A(Cr[3]),
    .SLEEP(Cr[4]),
    .X(_144_)
  );
  sky130_fd_sc_hd__a31oi_1 _212_ (
    .A1(_111_),
    .A2(Cr[1]),
    .A3(_121_),
    .B1(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a21oi_1 _213_ (
    .A1(_139_),
    .A2(_141_),
    .B1(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _214_ (
    .A(Cr[1]),
    .SLEEP(_122_),
    .X(_147_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _215_ (
    .A(_144_),
    .SLEEP(Cr[2]),
    .X(_148_)
  );
  sky130_fd_sc_hd__or3b_1 _216_ (
    .A(Dr[4]),
    .B(Dr[2]),
    .C_N(Dr[3]),
    .X(_149_)
  );
  sky130_fd_sc_hd__o221ai_1 _217_ (
    .A1(Dr[3]),
    .A2(_140_),
    .B1(_141_),
    .B2(Dr[0]),
    .C1(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor4_1 _218_ (
    .A(_143_),
    .B(_147_),
    .C(_148_),
    .D(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__xnor2_1 _219_ (
    .A(_142_),
    .B(_145_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__a21oi_1 _220_ (
    .A1(_151_),
    .A2(_152_),
    .B1(_146_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__xor2_1 _221_ (
    .A(_138_),
    .B(_153_),
    .X(_154_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _222_ (
    .A(Ar[3]),
    .SLEEP(Ar[4]),
    .X(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _223_ (
    .A(Ar[3]),
    .B(Ar[2]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor4b_1 _224_ (
    .A(Ar[3]),
    .B(Ar[4]),
    .C(Ar[2]),
    .D_N(Ar[1]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _225_ (
    .A(Br[3]),
    .SLEEP(Br[4]),
    .X(_158_)
  );
  sky130_fd_sc_hd__nor4b_1 _226_ (
    .A(Br[3]),
    .B(Br[4]),
    .C(Br[2]),
    .D_N(Br[1]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__o22a_1 _227_ (
    .A1(_155_),
    .A2(_157_),
    .B1(_158_),
    .B2(_159_),
    .X(_160_)
  );
  sky130_fd_sc_hd__o22ai_1 _228_ (
    .A1(_155_),
    .A2(_157_),
    .B1(_158_),
    .B2(_159_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__or3b_1 _229_ (
    .A(Br[3]),
    .B(Br[4]),
    .C_N(Br[1]),
    .X(_162_)
  );
  sky130_fd_sc_hd__o21ai_0 _230_ (
    .A1(Br[4]),
    .A2(Br[2]),
    .B1(Br[3]),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a22o_1 _231_ (
    .A1(_113_),
    .A2(_159_),
    .B1(_162_),
    .B2(_163_),
    .X(_164_)
  );
  sky130_fd_sc_hd__or3b_1 _232_ (
    .A(Ar[3]),
    .B(Ar[4]),
    .C_N(Ar[1]),
    .X(_165_)
  );
  sky130_fd_sc_hd__o21ai_0 _233_ (
    .A1(Ar[4]),
    .A2(Ar[2]),
    .B1(Ar[3]),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a22o_1 _234_ (
    .A1(_112_),
    .A2(_157_),
    .B1(_165_),
    .B2(_166_),
    .X(_167_)
  );
  sky130_fd_sc_hd__nor4_1 _235_ (
    .A(_155_),
    .B(_157_),
    .C(_158_),
    .D(_159_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nor4_1 _236_ (
    .A(_160_),
    .B(_164_),
    .C(_167_),
    .D(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__o31ai_1 _237_ (
    .A1(_164_),
    .A2(_167_),
    .A3(_168_),
    .B1(_161_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nor2_1 _238_ (
    .A(Ar[4]),
    .B(_156_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nor2_1 _239_ (
    .A(Br[4]),
    .B(_116_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__xor2_1 _240_ (
    .A(_171_),
    .B(_172_),
    .X(_173_)
  );
  sky130_fd_sc_hd__xnor2_1 _241_ (
    .A(_170_),
    .B(_173_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor2_1 _242_ (
    .A(_154_),
    .B(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nand2_1 _243_ (
    .A(_154_),
    .B(_174_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__clkinv_1 _244_ (
    .A(_176_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nand2b_1 _245_ (
    .A_N(_175_),
    .B(_176_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__o22ai_1 _246_ (
    .A1(_164_),
    .A2(_167_),
    .B1(_168_),
    .B2(_160_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2b_1 _247_ (
    .A_N(_169_),
    .B(_001_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xor2_1 _248_ (
    .A(_151_),
    .B(_152_),
    .X(_003_)
  );
  sky130_fd_sc_hd__xor2_1 _249_ (
    .A(_164_),
    .B(_167_),
    .X(_004_)
  );
  sky130_fd_sc_hd__o31a_1 _250_ (
    .A1(_143_),
    .A2(_147_),
    .A3(_148_),
    .B1(_150_),
    .X(_005_)
  );
  sky130_fd_sc_hd__nor2_1 _251_ (
    .A(_151_),
    .B(_005_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor3_1 _252_ (
    .A(_151_),
    .B(_004_),
    .C(_005_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__maj3_1 _253_ (
    .A(_002_),
    .B(_003_),
    .C(_007_),
    .X(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _254_ (
    .A(Ar[4]),
    .B(Br[4]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__maj3_1 _255_ (
    .A(_170_),
    .B(_171_),
    .C(_172_),
    .X(_010_)
  );
  sky130_fd_sc_hd__a22o_1 _256_ (
    .A1(Ar[4]),
    .A2(Br[4]),
    .B1(_170_),
    .B2(_173_),
    .X(_011_)
  );
  sky130_fd_sc_hd__o21ai_0 _257_ (
    .A1(Ar[4]),
    .A2(Br[4]),
    .B1(_011_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _258_ (
    .A(Cr[4]),
    .B(Dr[4]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__xnor2_1 _259_ (
    .A(Cr[4]),
    .B(Dr[4]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nor3_1 _260_ (
    .A(_138_),
    .B(_153_),
    .C(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__o31ai_1 _261_ (
    .A1(_138_),
    .A2(_153_),
    .A3(_014_),
    .B1(_013_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _262_ (
    .A(_012_),
    .SLEEP(_016_),
    .X(_017_)
  );
  sky130_fd_sc_hd__o211a_1 _263_ (
    .A1(_138_),
    .A2(_153_),
    .B1(_014_),
    .C1(_136_),
    .X(_018_)
  );
  sky130_fd_sc_hd__nor2_1 _264_ (
    .A(_015_),
    .B(_018_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _265_ (
    .A(_009_),
    .B(_010_),
    .X(_020_)
  );
  sky130_fd_sc_hd__xnor2_1 _266_ (
    .A(_009_),
    .B(_010_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__o21ai_0 _267_ (
    .A1(_015_),
    .A2(_018_),
    .B1(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor3_1 _268_ (
    .A(_015_),
    .B(_018_),
    .C(_021_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _269_ (
    .A(_019_),
    .B(_020_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__xor2_1 _270_ (
    .A(_012_),
    .B(_016_),
    .X(_025_)
  );
  sky130_fd_sc_hd__xnor2_1 _271_ (
    .A(_002_),
    .B(_003_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _272_ (
    .A(_004_),
    .SLEEP(_006_),
    .X(_027_)
  );
  sky130_fd_sc_hd__nor2_1 _273_ (
    .A(_026_),
    .B(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor3_1 _274_ (
    .A(_007_),
    .B(_026_),
    .C(_027_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _275_ (
    .A(_025_),
    .B(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__maj3_1 _276_ (
    .A(_154_),
    .B(_174_),
    .C(_008_),
    .X(_031_)
  );
  sky130_fd_sc_hd__a221oi_1 _277_ (
    .A1(_012_),
    .A2(_016_),
    .B1(_022_),
    .B2(_031_),
    .C1(_023_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__o31ai_1 _278_ (
    .A1(_000_),
    .A2(_024_),
    .A3(_030_),
    .B1(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _279_ (
    .A(_017_),
    .B(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a21oi_1 _280_ (
    .A1(_002_),
    .A2(_003_),
    .B1(_028_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__mux2i_1 _281_ (
    .A0(_035_),
    .A1(_008_),
    .S(_034_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__xor2_1 _282_ (
    .A(_000_),
    .B(_036_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2i_1 _283_ (
    .A0(_027_),
    .A1(_007_),
    .S(_034_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xor2_1 _284_ (
    .A(_026_),
    .B(_038_),
    .X(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _285_ (
    .A(_037_),
    .B(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__o21ai_0 _286_ (
    .A1(_175_),
    .A2(_035_),
    .B1(_176_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a21oi_1 _287_ (
    .A1(_017_),
    .A2(_033_),
    .B1(_031_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__and3_1 _288_ (
    .A(_017_),
    .B(_033_),
    .C(_041_),
    .X(_043_)
  );
  sky130_fd_sc_hd__nor3_1 _289_ (
    .A(_024_),
    .B(_042_),
    .C(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o21a_1 _290_ (
    .A1(_042_),
    .A2(_043_),
    .B1(_024_),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor3_1 _291_ (
    .A(_000_),
    .B(_024_),
    .C(_035_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__a21o_1 _292_ (
    .A1(_177_),
    .A2(_022_),
    .B1(_023_),
    .X(_047_)
  );
  sky130_fd_sc_hd__o21ai_0 _293_ (
    .A1(_046_),
    .A2(_047_),
    .B1(_017_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a21oi_1 _294_ (
    .A1(_033_),
    .A2(_048_),
    .B1(_025_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor3_1 _295_ (
    .A(_044_),
    .B(_045_),
    .C(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor2_1 _296_ (
    .A(_003_),
    .B(_034_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a21oi_1 _297_ (
    .A1(_002_),
    .A2(_034_),
    .B1(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__and4_1 _298_ (
    .A(_037_),
    .B(_039_),
    .C(_050_),
    .D(_052_),
    .X(_053_)
  );
  sky130_fd_sc_hd__nand4_1 _299_ (
    .A(_037_),
    .B(_039_),
    .C(_050_),
    .D(_052_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o21a_1 _300_ (
    .A1(_029_),
    .A2(_037_),
    .B1(_050_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _301_ (
    .A0(_006_),
    .A1(_004_),
    .S(_034_),
    .X(_056_)
  );
  sky130_fd_sc_hd__a31o_1 _302_ (
    .A1(_037_),
    .A2(_039_),
    .A3(_050_),
    .B1(_052_),
    .X(_057_)
  );
  sky130_fd_sc_hd__and4_1 _303_ (
    .A(_040_),
    .B(_052_),
    .C(_055_),
    .D(_056_),
    .X(_058_)
  );
  sky130_fd_sc_hd__a41oi_1 _304_ (
    .A1(_040_),
    .A2(_052_),
    .A3(_055_),
    .A4(_056_),
    .B1(_053_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _305_ (
    .A(_174_),
    .B(_034_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__o21ai_0 _306_ (
    .A1(_154_),
    .A2(_034_),
    .B1(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _307_ (
    .A(_059_),
    .SLEEP(_061_),
    .X(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _308_ (
    .A(_020_),
    .B(_034_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__o21ai_0 _309_ (
    .A1(_019_),
    .A2(_034_),
    .B1(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor3_1 _310_ (
    .A(_059_),
    .B(_061_),
    .C(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a211oi_1 _311_ (
    .A1(_062_),
    .A2(_064_),
    .B1(_065_),
    .C1(_127_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__o21ai_0 _312_ (
    .A1(_126_),
    .A2(_020_),
    .B1(_120_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__o221ai_1 _313_ (
    .A1(_120_),
    .A2(_019_),
    .B1(_066_),
    .B2(_067_),
    .C1(_128_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _314_ (
    .A(_129_),
    .B(_131_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _315_ (
    .A(_068_),
    .B(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _316_ (
    .A(Vr[3]),
    .SLEEP(_132_),
    .X(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _317_ (
    .A(_129_),
    .B(_130_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a2111oi_0 _318_ (
    .A1(Vr[2]),
    .A2(_133_),
    .B1(_071_),
    .C1(_072_),
    .D1(Vr[10]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__a21oi_1 _319_ (
    .A1(_059_),
    .A2(_061_),
    .B1(_127_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o21ai_0 _320_ (
    .A1(_126_),
    .A2(_174_),
    .B1(_120_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a21oi_1 _321_ (
    .A1(_062_),
    .A2(_074_),
    .B1(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a21oi_1 _322_ (
    .A1(_126_),
    .A2(_154_),
    .B1(_120_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor2_1 _323_ (
    .A(_076_),
    .B(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _324_ (
    .A(Vr[1]),
    .B(_133_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2b_1 _325_ (
    .A_N(Vr[10]),
    .B(Vr[9]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__a21oi_1 _326_ (
    .A1(_114_),
    .A2(Vr[5]),
    .B1(Vr[7]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__o221ai_1 _327_ (
    .A1(Vr[2]),
    .A2(_079_),
    .B1(_081_),
    .B2(_129_),
    .C1(_080_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor2_1 _328_ (
    .A(_071_),
    .B(_082_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a32oi_1 _329_ (
    .A1(_040_),
    .A2(_055_),
    .A3(_056_),
    .B1(_057_),
    .B2(_054_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor3_1 _330_ (
    .A(_127_),
    .B(_058_),
    .C(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o21ai_0 _331_ (
    .A1(_126_),
    .A2(_002_),
    .B1(_120_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o221a_1 _332_ (
    .A1(_120_),
    .A2(_003_),
    .B1(_085_),
    .B2(_086_),
    .C1(_128_),
    .X(_087_)
  );
  sky130_fd_sc_hd__a21o_1 _333_ (
    .A1(_040_),
    .A2(_055_),
    .B1(_056_),
    .X(_088_)
  );
  sky130_fd_sc_hd__a31oi_1 _334_ (
    .A1(_040_),
    .A2(_055_),
    .A3(_056_),
    .B1(_127_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand2_1 _335_ (
    .A(_127_),
    .B(_004_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2_1 _336_ (
    .A(_120_),
    .B(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a21oi_1 _337_ (
    .A1(_088_),
    .A2(_089_),
    .B1(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a21oi_1 _338_ (
    .A1(_115_),
    .A2(Vr[2]),
    .B1(Vr[4]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor2_1 _339_ (
    .A(Vr[5]),
    .B(Vr[3]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor3_1 _340_ (
    .A(Vr[7]),
    .B(_093_),
    .C(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nor3_1 _341_ (
    .A(Vr[8]),
    .B(Vr[6]),
    .C(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a21oi_1 _342_ (
    .A1(Vr[6]),
    .A2(_115_),
    .B1(Vr[8]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor2_1 _343_ (
    .A(Vr[7]),
    .B(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor3_1 _344_ (
    .A(Vr[10]),
    .B(_096_),
    .C(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__o22ai_1 _345_ (
    .A1(Vr[8]),
    .A2(_080_),
    .B1(_099_),
    .B2(Vr[9]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor3_1 _346_ (
    .A(Vr[2]),
    .B(Vr[0]),
    .C(_079_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__a21oi_1 _347_ (
    .A1(_079_),
    .A2(_100_),
    .B1(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a21oi_1 _348_ (
    .A1(_126_),
    .A2(_006_),
    .B1(_120_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor3_1 _349_ (
    .A(_092_),
    .B(_102_),
    .C(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__maj3_1 _350_ (
    .A(_083_),
    .B(_087_),
    .C(_104_),
    .X(_105_)
  );
  sky130_fd_sc_hd__maj3_1 _351_ (
    .A(_073_),
    .B(_078_),
    .C(_105_),
    .X(_106_)
  );
  sky130_fd_sc_hd__nor3b_1 _352_ (
    .A(_065_),
    .B(_016_),
    .C_N(_012_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__o22ai_1 _353_ (
    .A1(_068_),
    .A2(_069_),
    .B1(_107_),
    .B2(_129_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a21oi_1 _354_ (
    .A1(_070_),
    .A2(_106_),
    .B1(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__a21o_1 _355_ (
    .A1(_129_),
    .A2(_107_),
    .B1(_134_),
    .X(_110_)
  );
  sky130_fd_sc_hd__o21ai_0 _356_ (
    .A1(_109_),
    .A2(_110_),
    .B1(_135_),
    .Y(spike_c)
  );
  sky130_fd_sc_hd__dfxtp_1 _357_ (
    .CLK(clk),
    .D(spike_c),
    .Q(spike)
  );
  sky130_fd_sc_hd__dfxtp_1 _358_ (
    .CLK(clk),
    .D(A[0]),
    .Q(Ar[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _359_ (
    .CLK(clk),
    .D(A[1]),
    .Q(Ar[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _360_ (
    .CLK(clk),
    .D(A[2]),
    .Q(Ar[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _361_ (
    .CLK(clk),
    .D(A[3]),
    .Q(Ar[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _362_ (
    .CLK(clk),
    .D(A[4]),
    .Q(Ar[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _363_ (
    .CLK(clk),
    .D(B[0]),
    .Q(Br[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _364_ (
    .CLK(clk),
    .D(B[1]),
    .Q(Br[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _365_ (
    .CLK(clk),
    .D(B[2]),
    .Q(Br[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _366_ (
    .CLK(clk),
    .D(B[3]),
    .Q(Br[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _367_ (
    .CLK(clk),
    .D(B[4]),
    .Q(Br[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _368_ (
    .CLK(clk),
    .D(C[0]),
    .Q(Cr[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _369_ (
    .CLK(clk),
    .D(C[1]),
    .Q(Cr[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _370_ (
    .CLK(clk),
    .D(C[2]),
    .Q(Cr[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _371_ (
    .CLK(clk),
    .D(C[3]),
    .Q(Cr[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _372_ (
    .CLK(clk),
    .D(C[4]),
    .Q(Cr[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _373_ (
    .CLK(clk),
    .D(D[0]),
    .Q(Dr[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _374_ (
    .CLK(clk),
    .D(D[1]),
    .Q(Dr[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _375_ (
    .CLK(clk),
    .D(D[2]),
    .Q(Dr[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _376_ (
    .CLK(clk),
    .D(D[3]),
    .Q(Dr[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _377_ (
    .CLK(clk),
    .D(D[4]),
    .Q(Dr[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _378_ (
    .CLK(clk),
    .D(Vth[0]),
    .Q(Vr[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _379_ (
    .CLK(clk),
    .D(Vth[1]),
    .Q(Vr[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _380_ (
    .CLK(clk),
    .D(Vth[2]),
    .Q(Vr[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _381_ (
    .CLK(clk),
    .D(Vth[3]),
    .Q(Vr[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _382_ (
    .CLK(clk),
    .D(Vth[4]),
    .Q(Vr[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _383_ (
    .CLK(clk),
    .D(Vth[5]),
    .Q(Vr[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _384_ (
    .CLK(clk),
    .D(Vth[6]),
    .Q(Vr[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _385_ (
    .CLK(clk),
    .D(Vth[7]),
    .Q(Vr[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _386_ (
    .CLK(clk),
    .D(Vth[8]),
    .Q(Vr[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _387_ (
    .CLK(clk),
    .D(Vth[9]),
    .Q(Vr[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _388_ (
    .CLK(clk),
    .D(Vth[10]),
    .Q(Vr[10])
  );
  assign \ADD.X [5] = 1'h0;
  assign \ADD.Y [5] = 1'h0;
  assign \ADD.d [5] = 1'hx;
  assign \ADD.mx [5] = 1'h0;
  assign \ADD.s [6] = 1'h0;
  assign \LA.i  = 32'd4294967295;
  assign \LA.v  = Ar;
  assign \LB.i  = 32'd4294967295;
  assign \LB.v  = Br;
  assign \LC.i  = 32'd4294967295;
  assign \LC.v  = Cr;
  assign \LD.i  = 32'd4294967295;
  assign \LD.v  = Dr;
  assign \LV.i  = 32'd4294967295;
  assign \LV.v  = Vr;
  assign X = \ADD.X [4:0];
  assign Y = \ADD.Y [4:0];
  assign s = { 1'h0, \ADD.s [5:0] };
endmodule
