/* Generated by Yosys 0.55 (git sha1 60f126cd0, ccache clang 18.1.3 -O3 -flto -flto) */

module mult_detector(clk, A, B, C, D, Vth, spike);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  input [4:0] A;
  wire [4:0] A;
  wire [4:0] Ar;
  input [4:0] B;
  wire [4:0] B;
  wire [4:0] Br;
  input [4:0] C;
  wire [4:0] C;
  wire [4:0] Cr;
  input [4:0] D;
  wire [4:0] D;
  wire [4:0] Dr;
  wire [10:0] Vr;
  input [10:0] Vth;
  wire [10:0] Vth;
  input clk;
  wire clk;
  wire [9:0] p1;
  wire [9:0] p2;
  output spike;
  wire spike;
  wire spike_c;
  sky130_fd_sc_hd__clkinv_1 _231_ (
    .A(Vr[9]),
    .Y(_164_)
  );
  sky130_fd_sc_hd__clkinv_1 _232_ (
    .A(Vr[7]),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(Ar[4]),
    .B(Br[0]),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nand2_1 _234_ (
    .A(Br[3]),
    .B(Ar[1]),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(Ar[1]),
    .B(Br[0]),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(Ar[3]),
    .B(Br[1]),
    .Y(_169_)
  );
  sky130_fd_sc_hd__maj3_1 _237_ (
    .A(_166_),
    .B(_167_),
    .C(_169_),
    .X(_170_)
  );
  sky130_fd_sc_hd__and2_0 _238_ (
    .A(Br[1]),
    .B(Ar[2]),
    .X(_171_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(Br[1]),
    .B(Ar[2]),
    .Y(_172_)
  );
  sky130_fd_sc_hd__nand4_1 _240_ (
    .A(Br[3]),
    .B(Ar[4]),
    .C(Br[1]),
    .D(Ar[2]),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a22o_1 _241_ (
    .A1(Ar[4]),
    .A2(Br[1]),
    .B1(Ar[2]),
    .B2(Br[3]),
    .X(_174_)
  );
  sky130_fd_sc_hd__nand2_1 _242_ (
    .A(_173_),
    .B(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nand4_1 _243_ (
    .A(Ar[3]),
    .B(Br[2]),
    .C(Br[4]),
    .D(Ar[1]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__a22o_1 _244_ (
    .A1(Ar[3]),
    .A2(Br[2]),
    .B1(Br[4]),
    .B2(Ar[1]),
    .X(_177_)
  );
  sky130_fd_sc_hd__nand2_1 _245_ (
    .A(_176_),
    .B(_177_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__maj3_1 _246_ (
    .A(_170_),
    .B(_175_),
    .C(_178_),
    .X(_179_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _247_ (
    .A(Ar[3]),
    .SLEEP(_173_),
    .X(_180_)
  );
  sky130_fd_sc_hd__nand2_1 _248_ (
    .A(Br[3]),
    .B(Ar[3]),
    .Y(_181_)
  );
  sky130_fd_sc_hd__mux2i_1 _249_ (
    .A0(Ar[3]),
    .A1(_181_),
    .S(_173_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__and2_0 _250_ (
    .A(Ar[2]),
    .B(Br[2]),
    .X(_183_)
  );
  sky130_fd_sc_hd__nand4_1 _251_ (
    .A(Ar[4]),
    .B(Ar[2]),
    .C(Br[2]),
    .D(Br[4]),
    .Y(_184_)
  );
  sky130_fd_sc_hd__a22o_1 _252_ (
    .A1(Ar[4]),
    .A2(Br[2]),
    .B1(Br[4]),
    .B2(Ar[2]),
    .X(_185_)
  );
  sky130_fd_sc_hd__nand2_1 _253_ (
    .A(_184_),
    .B(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__xor2_1 _254_ (
    .A(_182_),
    .B(_186_),
    .X(_187_)
  );
  sky130_fd_sc_hd__nor2_1 _255_ (
    .A(_179_),
    .B(_187_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__xor2_1 _256_ (
    .A(_179_),
    .B(_187_),
    .X(_189_)
  );
  sky130_fd_sc_hd__nand2_1 _257_ (
    .A(Cr[3]),
    .B(Dr[2]),
    .Y(_190_)
  );
  sky130_fd_sc_hd__nand2_1 _258_ (
    .A(Cr[4]),
    .B(Dr[1]),
    .Y(_191_)
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(Cr[4]),
    .B(Dr[2]),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nand2_1 _260_ (
    .A(Cr[3]),
    .B(Dr[1]),
    .Y(_193_)
  );
  sky130_fd_sc_hd__nand2_1 _261_ (
    .A(Dr[3]),
    .B(Cr[2]),
    .Y(_194_)
  );
  sky130_fd_sc_hd__maj3_1 _262_ (
    .A(_190_),
    .B(_191_),
    .C(_194_),
    .X(_195_)
  );
  sky130_fd_sc_hd__nand2_1 _263_ (
    .A(Dr[3]),
    .B(Cr[3]),
    .Y(_196_)
  );
  sky130_fd_sc_hd__xnor2_1 _264_ (
    .A(_192_),
    .B(_196_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__xor2_1 _265_ (
    .A(_176_),
    .B(_197_),
    .X(_198_)
  );
  sky130_fd_sc_hd__xnor2_1 _266_ (
    .A(_195_),
    .B(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__a21oi_1 _267_ (
    .A1(_189_),
    .A2(_199_),
    .B1(_188_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__a31oi_1 _268_ (
    .A1(_182_),
    .A2(_184_),
    .A3(_185_),
    .B1(_180_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nand4_1 _269_ (
    .A(Br[3]),
    .B(Ar[4]),
    .C(Ar[3]),
    .D(Br[4]),
    .Y(_202_)
  );
  sky130_fd_sc_hd__a22oi_1 _270_ (
    .A1(Br[3]),
    .A2(Ar[4]),
    .B1(Ar[3]),
    .B2(Br[4]),
    .Y(_203_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _271_ (
    .A(_202_),
    .SLEEP(_203_),
    .X(_204_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _272_ (
    .A(_204_),
    .SLEEP(_201_),
    .X(_205_)
  );
  sky130_fd_sc_hd__xnor2_1 _273_ (
    .A(_201_),
    .B(_204_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(Dr[3]),
    .B(Cr[4]),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nand3_1 _275_ (
    .A(Dr[3]),
    .B(Cr[4]),
    .C(_190_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__xor2_1 _276_ (
    .A(_184_),
    .B(_208_),
    .X(_209_)
  );
  sky130_fd_sc_hd__xnor2_1 _277_ (
    .A(_206_),
    .B(_209_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__xor2_1 _278_ (
    .A(_200_),
    .B(_210_),
    .X(_211_)
  );
  sky130_fd_sc_hd__maj3_1 _279_ (
    .A(_176_),
    .B(_195_),
    .C(_197_),
    .X(_212_)
  );
  sky130_fd_sc_hd__maj3_1 _280_ (
    .A(_200_),
    .B(_210_),
    .C(_212_),
    .X(_213_)
  );
  sky130_fd_sc_hd__a21oi_1 _281_ (
    .A1(_206_),
    .A2(_209_),
    .B1(_205_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nand3_1 _282_ (
    .A(Ar[4]),
    .B(Br[4]),
    .C(_181_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _283_ (
    .A(_214_),
    .SLEEP(_215_),
    .X(_216_)
  );
  sky130_fd_sc_hd__xor2_1 _284_ (
    .A(_214_),
    .B(_215_),
    .X(_217_)
  );
  sky130_fd_sc_hd__a21oi_1 _285_ (
    .A1(_184_),
    .A2(_190_),
    .B1(_207_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nand2_1 _286_ (
    .A(_217_),
    .B(_218_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__xnor2_1 _287_ (
    .A(_217_),
    .B(_218_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__xnor2_1 _288_ (
    .A(_213_),
    .B(_220_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand2_1 _289_ (
    .A(Cr[4]),
    .B(Dr[4]),
    .Y(_222_)
  );
  sky130_fd_sc_hd__maj3_1 _290_ (
    .A(_213_),
    .B(_220_),
    .C(_222_),
    .X(_223_)
  );
  sky130_fd_sc_hd__nor2_1 _291_ (
    .A(_202_),
    .B(_219_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__a31oi_1 _292_ (
    .A1(_202_),
    .A2(_216_),
    .A3(_219_),
    .B1(_224_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _293_ (
    .A(_225_),
    .SLEEP(_223_),
    .X(_226_)
  );
  sky130_fd_sc_hd__xnor2_1 _294_ (
    .A(_223_),
    .B(_225_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__clkinv_1 _295_ (
    .A(_227_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__xnor3_1 _296_ (
    .A(_166_),
    .B(_167_),
    .C(_169_),
    .X(_229_)
  );
  sky130_fd_sc_hd__nand2_1 _297_ (
    .A(Br[0]),
    .B(Ar[0]),
    .Y(_230_)
  );
  sky130_fd_sc_hd__nand4_1 _298_ (
    .A(Br[3]),
    .B(Ar[3]),
    .C(Br[0]),
    .D(Ar[0]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__a22o_1 _299_ (
    .A1(Ar[3]),
    .A2(Br[0]),
    .B1(Ar[0]),
    .B2(Br[3]),
    .X(_001_)
  );
  sky130_fd_sc_hd__a21boi_0 _300_ (
    .A1(_172_),
    .A2(_000_),
    .B1_N(_001_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__and2_0 _301_ (
    .A(Cr[4]),
    .B(Dr[0]),
    .X(_003_)
  );
  sky130_fd_sc_hd__and2_0 _302_ (
    .A(Br[4]),
    .B(Ar[0]),
    .X(_004_)
  );
  sky130_fd_sc_hd__xor3_1 _303_ (
    .A(_183_),
    .B(_003_),
    .C(_004_),
    .X(_005_)
  );
  sky130_fd_sc_hd__maj3_1 _304_ (
    .A(_229_),
    .B(_002_),
    .C(_005_),
    .X(_006_)
  );
  sky130_fd_sc_hd__xnor3_1 _305_ (
    .A(_170_),
    .B(_175_),
    .C(_178_),
    .X(_007_)
  );
  sky130_fd_sc_hd__xnor2_1 _306_ (
    .A(_006_),
    .B(_007_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(Dr[2]),
    .B(Cr[2]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _308_ (
    .A(Dr[1]),
    .B(Cr[2]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__xor2_1 _309_ (
    .A(_193_),
    .B(_009_),
    .X(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _310_ (
    .A(Dr[3]),
    .B(Cr[1]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__maj3_1 _311_ (
    .A(_193_),
    .B(_009_),
    .C(_012_),
    .X(_013_)
  );
  sky130_fd_sc_hd__xnor3_1 _312_ (
    .A(_190_),
    .B(_191_),
    .C(_194_),
    .X(_014_)
  );
  sky130_fd_sc_hd__maj3_1 _313_ (
    .A(_183_),
    .B(_003_),
    .C(_004_),
    .X(_015_)
  );
  sky130_fd_sc_hd__xor2_1 _314_ (
    .A(_014_),
    .B(_015_),
    .X(_016_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _315_ (
    .A(_016_),
    .SLEEP(_013_),
    .X(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _316_ (
    .A(_013_),
    .B(_016_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__maj3_1 _317_ (
    .A(_006_),
    .B(_007_),
    .C(_018_),
    .X(_019_)
  );
  sky130_fd_sc_hd__xnor2_1 _318_ (
    .A(_189_),
    .B(_199_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _319_ (
    .A(_019_),
    .SLEEP(_020_),
    .X(_021_)
  );
  sky130_fd_sc_hd__xor2_1 _320_ (
    .A(_019_),
    .B(_020_),
    .X(_022_)
  );
  sky130_fd_sc_hd__a21oi_1 _321_ (
    .A1(_014_),
    .A2(_015_),
    .B1(_017_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _322_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor2_1 _323_ (
    .A(_021_),
    .B(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__xor2_1 _324_ (
    .A(_211_),
    .B(_212_),
    .X(_026_)
  );
  sky130_fd_sc_hd__xor2_1 _325_ (
    .A(_025_),
    .B(_026_),
    .X(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _326_ (
    .A(Cr[3]),
    .B(Dr[4]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__maj3_1 _327_ (
    .A(_025_),
    .B(_026_),
    .C(_028_),
    .X(_029_)
  );
  sky130_fd_sc_hd__xor2_1 _328_ (
    .A(_221_),
    .B(_222_),
    .X(_030_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _329_ (
    .A(_030_),
    .SLEEP(_029_),
    .X(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(_000_),
    .B(_001_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _331_ (
    .A(Ar[2]),
    .B(Br[0]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _332_ (
    .A(Br[1]),
    .B(Ar[1]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor2_1 _333_ (
    .A(_168_),
    .B(_172_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand4_1 _334_ (
    .A(Br[2]),
    .B(Cr[3]),
    .C(Ar[1]),
    .D(Dr[0]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a22oi_1 _335_ (
    .A1(Br[2]),
    .A2(Ar[1]),
    .B1(Dr[0]),
    .B2(Cr[3]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _336_ (
    .A(_036_),
    .SLEEP(_037_),
    .X(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _337_ (
    .A1(Ar[1]),
    .A2(Br[0]),
    .B1(_172_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand4_1 _338_ (
    .A(_168_),
    .B(_171_),
    .C(_000_),
    .D(_001_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a22o_1 _339_ (
    .A1(_168_),
    .A2(_171_),
    .B1(_000_),
    .B2(_001_),
    .X(_041_)
  );
  sky130_fd_sc_hd__a32oi_1 _340_ (
    .A1(_038_),
    .A2(_040_),
    .A3(_041_),
    .B1(_035_),
    .B2(_032_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__xor3_1 _341_ (
    .A(_229_),
    .B(_002_),
    .C(_005_),
    .X(_043_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _342_ (
    .A(_043_),
    .SLEEP(_042_),
    .X(_044_)
  );
  sky130_fd_sc_hd__xnor2_1 _343_ (
    .A(_042_),
    .B(_043_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _344_ (
    .A(Dr[2]),
    .B(Cr[1]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__xor2_1 _345_ (
    .A(_010_),
    .B(_046_),
    .X(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _346_ (
    .A(Dr[3]),
    .B(Cr[0]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__maj3_1 _347_ (
    .A(_010_),
    .B(_046_),
    .C(_048_),
    .X(_049_)
  );
  sky130_fd_sc_hd__xor2_1 _348_ (
    .A(_011_),
    .B(_012_),
    .X(_050_)
  );
  sky130_fd_sc_hd__xnor3_1 _349_ (
    .A(_011_),
    .B(_012_),
    .C(_036_),
    .X(_051_)
  );
  sky130_fd_sc_hd__xor2_1 _350_ (
    .A(_049_),
    .B(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd__a21oi_1 _351_ (
    .A1(_045_),
    .A2(_052_),
    .B1(_044_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__xnor2_1 _352_ (
    .A(_008_),
    .B(_018_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__clkinv_1 _353_ (
    .A(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__xor2_1 _354_ (
    .A(_053_),
    .B(_054_),
    .X(_056_)
  );
  sky130_fd_sc_hd__maj3_1 _355_ (
    .A(_036_),
    .B(_049_),
    .C(_050_),
    .X(_057_)
  );
  sky130_fd_sc_hd__maj3_1 _356_ (
    .A(_053_),
    .B(_055_),
    .C(_057_),
    .X(_058_)
  );
  sky130_fd_sc_hd__xnor2_1 _357_ (
    .A(_022_),
    .B(_023_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__xnor2_1 _358_ (
    .A(_058_),
    .B(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _359_ (
    .A(Cr[2]),
    .B(Dr[4]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__maj3_1 _360_ (
    .A(_058_),
    .B(_059_),
    .C(_061_),
    .X(_062_)
  );
  sky130_fd_sc_hd__xnor2_1 _361_ (
    .A(_027_),
    .B(_028_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2b_1 _362_ (
    .A_N(_062_),
    .B(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__xor2_1 _363_ (
    .A(_033_),
    .B(_034_),
    .X(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _364_ (
    .A(Br[1]),
    .B(Ar[0]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nor2_1 _365_ (
    .A(_230_),
    .B(_034_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand4_1 _366_ (
    .A(Br[2]),
    .B(Cr[2]),
    .C(Ar[0]),
    .D(Dr[0]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a22oi_1 _367_ (
    .A1(Br[2]),
    .A2(Ar[0]),
    .B1(Dr[0]),
    .B2(Cr[2]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _368_ (
    .A(_068_),
    .SLEEP(_069_),
    .X(_070_)
  );
  sky130_fd_sc_hd__maj3_1 _369_ (
    .A(_065_),
    .B(_067_),
    .C(_070_),
    .X(_071_)
  );
  sky130_fd_sc_hd__xnor3_1 _370_ (
    .A(_032_),
    .B(_038_),
    .C(_039_),
    .X(_072_)
  );
  sky130_fd_sc_hd__xnor2_1 _371_ (
    .A(_071_),
    .B(_072_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _372_ (
    .A(Dr[1]),
    .B(Cr[0]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand4_1 _373_ (
    .A(Dr[2]),
    .B(Dr[1]),
    .C(Cr[1]),
    .D(Cr[0]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__xor2_1 _374_ (
    .A(_047_),
    .B(_048_),
    .X(_076_)
  );
  sky130_fd_sc_hd__xnor3_1 _375_ (
    .A(_047_),
    .B(_048_),
    .C(_068_),
    .X(_077_)
  );
  sky130_fd_sc_hd__xor2_1 _376_ (
    .A(_075_),
    .B(_077_),
    .X(_078_)
  );
  sky130_fd_sc_hd__maj3_1 _377_ (
    .A(_071_),
    .B(_072_),
    .C(_078_),
    .X(_079_)
  );
  sky130_fd_sc_hd__clkinv_1 _378_ (
    .A(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__xnor2_1 _379_ (
    .A(_045_),
    .B(_052_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__maj3_1 _380_ (
    .A(_068_),
    .B(_075_),
    .C(_076_),
    .X(_082_)
  );
  sky130_fd_sc_hd__xor2_1 _381_ (
    .A(_079_),
    .B(_081_),
    .X(_083_)
  );
  sky130_fd_sc_hd__maj3_1 _382_ (
    .A(_080_),
    .B(_081_),
    .C(_082_),
    .X(_084_)
  );
  sky130_fd_sc_hd__xnor2_1 _383_ (
    .A(_056_),
    .B(_057_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _384_ (
    .A(Dr[4]),
    .B(Cr[1]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__xor2_1 _385_ (
    .A(_084_),
    .B(_085_),
    .X(_087_)
  );
  sky130_fd_sc_hd__maj3_1 _386_ (
    .A(_084_),
    .B(_085_),
    .C(_086_),
    .X(_088_)
  );
  sky130_fd_sc_hd__xor2_1 _387_ (
    .A(_060_),
    .B(_061_),
    .X(_089_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _388_ (
    .A(_089_),
    .SLEEP(_088_),
    .X(_090_)
  );
  sky130_fd_sc_hd__xnor2_1 _389_ (
    .A(_082_),
    .B(_083_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__xnor3_1 _390_ (
    .A(_065_),
    .B(_067_),
    .C(_070_),
    .X(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _391_ (
    .A(Dr[0]),
    .B(Cr[1]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__xor2_1 _392_ (
    .A(_168_),
    .B(_066_),
    .X(_094_)
  );
  sky130_fd_sc_hd__nand3_1 _393_ (
    .A(Dr[0]),
    .B(Cr[1]),
    .C(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a22o_1 _394_ (
    .A1(Dr[1]),
    .A2(Cr[1]),
    .B1(Cr[0]),
    .B2(Dr[2]),
    .X(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _395_ (
    .A(_075_),
    .B(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__maj3_1 _396_ (
    .A(_092_),
    .B(_095_),
    .C(_097_),
    .X(_098_)
  );
  sky130_fd_sc_hd__xor2_1 _397_ (
    .A(_073_),
    .B(_078_),
    .X(_099_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _398_ (
    .A(_098_),
    .SLEEP(_099_),
    .X(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _399_ (
    .A(Dr[4]),
    .B(Cr[0]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__maj3_1 _400_ (
    .A(_091_),
    .B(_100_),
    .C(_101_),
    .X(_102_)
  );
  sky130_fd_sc_hd__clkinv_1 _401_ (
    .A(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__xnor2_1 _402_ (
    .A(_086_),
    .B(_087_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__xnor3_1 _403_ (
    .A(_073_),
    .B(_078_),
    .C(_098_),
    .X(_105_)
  );
  sky130_fd_sc_hd__xor2_1 _404_ (
    .A(_093_),
    .B(_094_),
    .X(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _405_ (
    .A(Dr[0]),
    .B(Cr[0]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand4_1 _406_ (
    .A(Br[0]),
    .B(Ar[0]),
    .C(Dr[0]),
    .D(Cr[0]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__xnor2_1 _407_ (
    .A(_106_),
    .B(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__maj3_1 _408_ (
    .A(_074_),
    .B(_106_),
    .C(_108_),
    .X(_110_)
  );
  sky130_fd_sc_hd__xnor3_1 _409_ (
    .A(_092_),
    .B(_095_),
    .C(_097_),
    .X(_111_)
  );
  sky130_fd_sc_hd__nand2b_1 _410_ (
    .A_N(_110_),
    .B(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nor2_1 _411_ (
    .A(_105_),
    .B(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__xnor3_1 _412_ (
    .A(_091_),
    .B(_100_),
    .C(_101_),
    .X(_114_)
  );
  sky130_fd_sc_hd__and2_0 _413_ (
    .A(_113_),
    .B(_114_),
    .X(_115_)
  );
  sky130_fd_sc_hd__xor3_1 _414_ (
    .A(_086_),
    .B(_087_),
    .C(_102_),
    .X(_116_)
  );
  sky130_fd_sc_hd__maj3_1 _415_ (
    .A(_103_),
    .B(_104_),
    .C(_115_),
    .X(_117_)
  );
  sky130_fd_sc_hd__xnor2_1 _416_ (
    .A(_088_),
    .B(_089_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__a21oi_1 _417_ (
    .A1(_117_),
    .A2(_118_),
    .B1(_090_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _418_ (
    .A(_062_),
    .SLEEP(_063_),
    .X(_120_)
  );
  sky130_fd_sc_hd__xnor2_1 _419_ (
    .A(_062_),
    .B(_063_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__o21ai_0 _420_ (
    .A1(_119_),
    .A2(_120_),
    .B1(_064_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__xnor2_1 _421_ (
    .A(_029_),
    .B(_030_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a21oi_1 _422_ (
    .A1(_122_),
    .A2(_123_),
    .B1(_031_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nor2_1 _423_ (
    .A(_224_),
    .B(_226_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__o21a_1 _424_ (
    .A1(_228_),
    .A2(_124_),
    .B1(_125_),
    .X(_126_)
  );
  sky130_fd_sc_hd__xnor2_1 _425_ (
    .A(_122_),
    .B(_123_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__xnor2_1 _426_ (
    .A(_119_),
    .B(_121_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nor2_1 _427_ (
    .A(_165_),
    .B(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__xnor2_1 _428_ (
    .A(_115_),
    .B(_116_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__xnor2_1 _429_ (
    .A(_113_),
    .B(_114_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand2_1 _430_ (
    .A(Vr[4]),
    .B(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__xnor3_1 _431_ (
    .A(Vr[5]),
    .B(_115_),
    .C(_116_),
    .X(_133_)
  );
  sky130_fd_sc_hd__and2_0 _432_ (
    .A(_132_),
    .B(_133_),
    .X(_134_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _433_ (
    .A(Vr[4]),
    .SLEEP(_131_),
    .X(_135_)
  );
  sky130_fd_sc_hd__xor2_1 _434_ (
    .A(_110_),
    .B(_111_),
    .X(_136_)
  );
  sky130_fd_sc_hd__xnor2_1 _435_ (
    .A(_105_),
    .B(_112_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__o22ai_1 _436_ (
    .A1(Vr[2]),
    .A2(_136_),
    .B1(_137_),
    .B2(Vr[3]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand2_1 _437_ (
    .A(Vr[2]),
    .B(_136_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__and2_0 _438_ (
    .A(Vr[3]),
    .B(_137_),
    .X(_140_)
  );
  sky130_fd_sc_hd__xnor2_1 _439_ (
    .A(_074_),
    .B(_109_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor2_1 _440_ (
    .A(Vr[1]),
    .B(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__xnor2_1 _441_ (
    .A(_230_),
    .B(_107_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nand2_1 _442_ (
    .A(Vr[0]),
    .B(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand2_1 _443_ (
    .A(Vr[1]),
    .B(_141_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nor3b_1 _444_ (
    .A(_140_),
    .B(_138_),
    .C_N(_139_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand4b_1 _445_ (
    .A_N(_142_),
    .B(_144_),
    .C(_145_),
    .D(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a21oi_1 _446_ (
    .A1(_139_),
    .A2(_142_),
    .B1(_138_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__o21ai_0 _447_ (
    .A1(_140_),
    .A2(_148_),
    .B1(_147_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand4_1 _448_ (
    .A(_132_),
    .B(_133_),
    .C(_135_),
    .D(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__maj3_1 _449_ (
    .A(Vr[5]),
    .B(_130_),
    .C(_135_),
    .X(_151_)
  );
  sky130_fd_sc_hd__nand2_1 _450_ (
    .A(_150_),
    .B(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__xnor2_1 _451_ (
    .A(_117_),
    .B(_118_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nor2_1 _452_ (
    .A(Vr[0]),
    .B(_143_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _453_ (
    .A(_147_),
    .B(_154_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a32oi_1 _454_ (
    .A1(_134_),
    .A2(_135_),
    .A3(_155_),
    .B1(_153_),
    .B2(Vr[6]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor2_1 _455_ (
    .A(Vr[6]),
    .B(_153_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__a221oi_1 _456_ (
    .A1(_165_),
    .A2(_128_),
    .B1(_152_),
    .B2(_156_),
    .C1(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__o22ai_1 _457_ (
    .A1(Vr[8]),
    .A2(_127_),
    .B1(_129_),
    .B2(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__xnor2_1 _458_ (
    .A(_227_),
    .B(_124_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nand2_1 _459_ (
    .A(Vr[8]),
    .B(_127_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__o211ai_1 _460_ (
    .A1(_164_),
    .A2(_160_),
    .B1(_161_),
    .C1(_159_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _461_ (
    .A1_N(Vr[10]),
    .A2_N(_126_),
    .B1(_160_),
    .B2(_164_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a22oi_1 _462_ (
    .A1(Vr[10]),
    .A2(_126_),
    .B1(_162_),
    .B2(_163_),
    .Y(spike_c)
  );
  sky130_fd_sc_hd__dfxtp_1 _463_ (
    .CLK(clk),
    .D(spike_c),
    .Q(spike)
  );
  sky130_fd_sc_hd__dfxtp_1 _464_ (
    .CLK(clk),
    .D(A[0]),
    .Q(Ar[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _465_ (
    .CLK(clk),
    .D(A[1]),
    .Q(Ar[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _466_ (
    .CLK(clk),
    .D(A[2]),
    .Q(Ar[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _467_ (
    .CLK(clk),
    .D(A[3]),
    .Q(Ar[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _468_ (
    .CLK(clk),
    .D(A[4]),
    .Q(Ar[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _469_ (
    .CLK(clk),
    .D(B[0]),
    .Q(Br[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _470_ (
    .CLK(clk),
    .D(B[1]),
    .Q(Br[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _471_ (
    .CLK(clk),
    .D(B[2]),
    .Q(Br[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _472_ (
    .CLK(clk),
    .D(B[3]),
    .Q(Br[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _473_ (
    .CLK(clk),
    .D(B[4]),
    .Q(Br[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _474_ (
    .CLK(clk),
    .D(C[0]),
    .Q(Cr[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _475_ (
    .CLK(clk),
    .D(C[1]),
    .Q(Cr[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _476_ (
    .CLK(clk),
    .D(C[2]),
    .Q(Cr[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _477_ (
    .CLK(clk),
    .D(C[3]),
    .Q(Cr[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _478_ (
    .CLK(clk),
    .D(C[4]),
    .Q(Cr[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _479_ (
    .CLK(clk),
    .D(D[0]),
    .Q(Dr[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _480_ (
    .CLK(clk),
    .D(D[1]),
    .Q(Dr[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _481_ (
    .CLK(clk),
    .D(D[2]),
    .Q(Dr[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _482_ (
    .CLK(clk),
    .D(D[3]),
    .Q(Dr[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _483_ (
    .CLK(clk),
    .D(D[4]),
    .Q(Dr[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _484_ (
    .CLK(clk),
    .D(Vth[0]),
    .Q(Vr[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _485_ (
    .CLK(clk),
    .D(Vth[1]),
    .Q(Vr[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _486_ (
    .CLK(clk),
    .D(Vth[2]),
    .Q(Vr[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _487_ (
    .CLK(clk),
    .D(Vth[3]),
    .Q(Vr[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _488_ (
    .CLK(clk),
    .D(Vth[4]),
    .Q(Vr[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _489_ (
    .CLK(clk),
    .D(Vth[5]),
    .Q(Vr[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _490_ (
    .CLK(clk),
    .D(Vth[6]),
    .Q(Vr[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _491_ (
    .CLK(clk),
    .D(Vth[7]),
    .Q(Vr[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _492_ (
    .CLK(clk),
    .D(Vth[8]),
    .Q(Vr[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _493_ (
    .CLK(clk),
    .D(Vth[9]),
    .Q(Vr[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _494_ (
    .CLK(clk),
    .D(Vth[10]),
    .Q(Vr[10])
  );
  assign p1 = 10'hxxx;
  assign p2 = 10'hxxx;
endmodule
